# encoding: UTF-8
# This file is auto-generated from the current state of the database. Instead
# of editing this file, please use the migrations feature of Active Record to
# incrementally modify your database, and then regenerate this schema definition.
#
# Note that this schema.rb definition is the authoritative source for your
# database schema. If you need to create the application database on another
# system, you should be using db:schema:load, not running all the migrations
# from scratch. The latter is a flawed and unsustainable approach (the more migrations
# you'll amass, the slower it'll run and the greater likelihood for issues).
#
# It's strongly recommended to check this file into your version control system.

ActiveRecord::Schema.define(:version => 20131101021522) do

  create_table "aisles", :force => true do |t|
    t.string   "client_id"
    t.integer  "sm_aisle_id"
    t.integer  "sm_zone_id"
    t.integer  "sm_warehouse_id"
    t.integer  "zone_id"
    t.string   "cl_aisle_id"
    t.string   "cl_zone_id"
    t.string   "cl_warehouse_id"
    t.string   "description"
    t.integer  "no_of_bays_aisle"
    t.integer  "no_of_levels_aisle"
    t.string   "attribute1"
    t.string   "attribute2"
    t.string   "attribute3"
    t.string   "attribute4"
    t.string   "attribute5"
    t.string   "attribute6"
    t.string   "attribute7"
    t.string   "attribute8"
    t.datetime "created_at",         :null => false
    t.datetime "updated_at",         :null => false
  end

  create_table "bays", :force => true do |t|
    t.string   "client_id"
    t.integer  "sm_bay_id"
    t.integer  "sm_aisle_id"
    t.integer  "sm_zone_id"
    t.integer  "sm_warehouse_id"
    t.integer  "aisle_id"
    t.string   "cl_bay_id"
    t.string   "cl_aisle_id"
    t.string   "cl_zone_id"
    t.string   "cl_warehouse_id"
    t.string   "description"
    t.integer  "no_of_level_bay"
    t.string   "attribute1"
    t.string   "attribute2"
    t.string   "attribute3"
    t.string   "attribute4"
    t.string   "attribute5"
    t.string   "attribute6"
    t.string   "attribute7"
    t.string   "attribute8"
    t.datetime "created_at",      :null => false
    t.datetime "updated_at",      :null => false
  end

  create_table "clients", :force => true do |t|
    t.string   "name_of_organization"
    t.integer  "address1"
    t.string   "address2"
    t.string   "zipcode"
    t.string   "state"
    t.string   "country"
    t.integer  "phone_no1"
    t.integer  "phone_no2"
    t.string   "email_id"
    t.string   "name_of_person"
    t.string   "status"
    t.string   "no_of_license_required"
    t.string   "attribute1"
    t.string   "attribute2"
    t.string   "attribute3"
    t.string   "attribute4"
    t.string   "attribute5"
    t.string   "attribute6"
    t.string   "attribute7"
    t.string   "attribute8"
    t.datetime "created_at",             :null => false
    t.datetime "updated_at",             :null => false
    t.string   "lastname_of_person"
  end

  create_table "itemmasters", :force => true do |t|
    t.string   "client_id"
    t.string   "item_number"
    t.string   "description"
    t.string   "velocity"
    t.integer  "case_quantity"
    t.string   "case_split_allowed"
    t.integer  "daily_avg_sales"
    t.integer  "weekly_avg_sales"
    t.integer  "monthly_avg_sales"
    t.string   "daily_forecast"
    t.string   "attribute1"
    t.string   "attribute2"
    t.string   "attribute3"
    t.string   "attribute4"
    t.string   "attribute5"
    t.string   "attribute6"
    t.string   "attribute7"
    t.string   "attribute8"
    t.datetime "created_at",         :null => false
    t.datetime "updated_at",         :null => false
  end

  create_table "levels", :force => true do |t|
    t.string   "client_id"
    t.integer  "sm_level_id"
    t.integer  "sm_bay_id"
    t.integer  "sm_aisle_id"
    t.integer  "sm_zone_id"
    t.integer  "sm_warehouse_id"
    t.integer  "bay_id"
    t.string   "cl_level_id"
    t.string   "cl_bay_id"
    t.string   "cl_aisle_id"
    t.string   "cl_zone_id"
    t.string   "cl_warehouse_id"
    t.string   "description"
    t.integer  "no_of_pos_level"
    t.string   "attribute1"
    t.string   "attribute2"
    t.string   "attribute3"
    t.string   "attribute4"
    t.string   "attribute5"
    t.string   "attribute6"
    t.string   "attribute7"
    t.string   "attribute8"
    t.datetime "created_at",      :null => false
    t.datetime "updated_at",      :null => false
  end

  add_index "levels", ["bay_id"], :name => "index_levels_on_bay_id"

  create_table "locationerrors", :force => true do |t|
    t.string   "client_id"
    t.integer  "transaction_id"
    t.integer  "sequence_no"
    t.string   "file_name"
    t.string   "error_code"
    t.string   "error_description"
    t.string   "attribute1"
    t.string   "attribute2"
    t.string   "attribute3"
    t.string   "attribute4"
    t.string   "attribute5"
    t.string   "attribute6"
    t.string   "attribute7"
    t.string   "attribute8"
    t.string   "attribute9"
    t.string   "attribute10"
    t.string   "attribute11"
    t.string   "attribute12"
    t.string   "attribute13"
    t.string   "attribute14"
    t.string   "attribute15"
    t.string   "attribute16"
    t.string   "attribute17"
    t.string   "attribute18"
    t.string   "attribute19"
    t.string   "attribute20"
    t.string   "attribute21"
    t.string   "attribute22"
    t.string   "attribute23"
    t.string   "attribute24"
    t.string   "attribute25"
    t.string   "attribute26"
    t.string   "attribute27"
    t.string   "attribute28"
    t.string   "attribute29"
    t.string   "attribute30"
    t.string   "attribute31"
    t.string   "attribute32"
    t.string   "attribute33"
    t.string   "attribute34"
    t.string   "attribute35"
    t.string   "attribute36"
    t.string   "attribute37"
    t.string   "attribute38"
    t.string   "attribute39"
    t.string   "attribute40"
    t.string   "attribute41"
    t.string   "attribute42"
    t.string   "attribute43"
    t.string   "attribute44"
    t.string   "attribute45"
    t.string   "attribute46"
    t.string   "attribute47"
    t.string   "attribute48"
    t.string   "attribute49"
    t.string   "attribute50"
    t.string   "attribute51"
    t.string   "attribute52"
    t.string   "attribute53"
    t.string   "attribute54"
    t.string   "attribute55"
    t.string   "attribute56"
    t.string   "attribute57"
    t.string   "attribute58"
    t.string   "attribute59"
    t.string   "attribute60"
    t.datetime "created_at",        :null => false
    t.datetime "updated_at",        :null => false
  end

  create_table "locations", :force => true do |t|
    t.string   "client_id"
    t.integer  "sm_loc_id"
    t.integer  "sm_pos_id"
    t.integer  "sm_level_id"
    t.integer  "sm_bay_id"
    t.integer  "sm_aisle_id"
    t.integer  "sm_zone_id"
    t.integer  "sm_warehouse_id"
    t.string   "sm_barcode"
    t.string   "cl_loc_id"
    t.string   "cl_pos_id"
    t.string   "cl_level_id"
    t.string   "cl_bay_id"
    t.string   "cl_aisle_id"
    t.string   "cl_zone_id"
    t.string   "cl_warehouse_id"
    t.string   "cl_barcode"
    t.string   "current_item"
    t.integer  "current_quantity"
    t.integer  "minimum_quantity"
    t.integer  "maximum_quantity"
    t.string   "status"
    t.integer  "life_time_total_picks"
    t.string   "attribute1"
    t.string   "attribute2"
    t.string   "attribute3"
    t.string   "attribute4"
    t.string   "attribute5"
    t.string   "attribute6"
    t.string   "attribute7"
    t.string   "attribute8"
    t.string   "attribute9"
    t.string   "attribute10"
    t.string   "attribute11"
    t.string   "attribute12"
    t.string   "attribute13"
    t.string   "attribute14"
    t.string   "attribute15"
    t.string   "attribute16"
    t.datetime "created_at",            :null => false
    t.datetime "updated_at",            :null => false
    t.string   "lock_code"
    t.string   "location_priority"
  end

  create_table "positions", :force => true do |t|
    t.string   "client_id"
    t.integer  "sm_pos_id"
    t.integer  "sm_level_id"
    t.integer  "sm_bay_id"
    t.integer  "sm_aisle_id"
    t.integer  "sm_zone_id"
    t.integer  "sm_warehouse_id"
    t.string   "sm_barcode"
    t.integer  "level_id"
    t.string   "cl_pos_id"
    t.string   "cl_level_id"
    t.string   "cl_bay_id"
    t.string   "cl_aisle_id"
    t.string   "cl_zone_id"
    t.string   "cl_warehouse_id"
    t.string   "cl_barcode"
    t.string   "description"
    t.string   "attribute1"
    t.string   "attribute2"
    t.string   "attribute3"
    t.string   "attribute4"
    t.string   "attribute5"
    t.string   "attribute6"
    t.string   "attribute7"
    t.string   "attribute8"
    t.string   "attribute9"
    t.string   "attribute10"
    t.string   "attribute11"
    t.string   "attribute12"
    t.string   "attribute13"
    t.string   "attribute14"
    t.string   "attribute15"
    t.string   "attribute16"
    t.datetime "created_at",      :null => false
    t.datetime "updated_at",      :null => false
  end

  add_index "positions", ["level_id"], :name => "index_positions_on_level_id"

  create_table "slottingrecommendations", :force => true do |t|
    t.string   "client_id"
    t.string   "item_number"
    t.string   "preffered_zone"
    t.string   "preffered_aisle"
    t.string   "preffered_bay"
    t.string   "preffered_level"
    t.string   "preffered_position"
    t.string   "partial_slotting"
    t.string   "preffered_slotting_rules"
    t.string   "location_recommended"
    t.string   "slotting_status"
    t.string   "attribute1"
    t.string   "attribute2"
    t.string   "attribute3"
    t.string   "attribute4"
    t.string   "attribute5"
    t.string   "attribute6"
    t.string   "attribute7"
    t.string   "attribute8"
    t.datetime "created_at",               :null => false
    t.datetime "updated_at",               :null => false
    t.string   "preffered_warehouse"
    t.integer  "quantity_to_be_slotted"
  end

  create_table "users", :force => true do |t|
    t.string   "client_id"
    t.integer  "contact_phone"
    t.string   "user_name"
    t.string   "user_id"
    t.string   "email_id"
    t.string   "password"
    t.string   "last_login"
    t.string   "status"
    t.string   "attribute1"
    t.string   "attribute2"
    t.string   "attribute3"
    t.string   "attribute4"
    t.string   "attribute5"
    t.string   "attribute6"
    t.string   "attribute7"
    t.string   "attribute8"
    t.datetime "created_at",     :null => false
    t.datetime "updated_at",     :null => false
    t.integer  "contact_phone2"
    t.string   "attribute9"
    t.string   "attribute10"
    t.string   "attribute11"
    t.string   "attribute12"
    t.string   "attribute13"
    t.string   "attribute14"
    t.string   "attribute15"
    t.string   "attribute16"
    t.string   "attribute17"
    t.string   "attribute18"
    t.string   "attribute19"
    t.string   "attribute20"
  end

  create_table "warehouses", :force => true do |t|
    t.string   "client_id"
    t.integer  "sm_warehouse_id"
    t.string   "cl_warehouse_id"
    t.string   "description"
    t.integer  "no_of_zones"
    t.string   "attribute1"
    t.string   "attribute2"
    t.string   "attribute3"
    t.string   "attribute4"
    t.string   "attribute5"
    t.string   "attribute6"
    t.string   "attribute7"
    t.string   "attribute8"
    t.datetime "created_at",      :null => false
    t.datetime "updated_at",      :null => false
  end

  create_table "zones", :force => true do |t|
    t.string   "client_id"
    t.integer  "sm_zone_id"
    t.integer  "sm_warehouse_id"
    t.integer  "warehouse_id"
    t.string   "cl_zone_id"
    t.string   "cl_warehouse_id"
    t.string   "description"
    t.integer  "no_of_aisles_zone"
    t.integer  "no_of_bays_aisle"
    t.integer  "no_of_levels_aisle"
    t.string   "attribute1"
    t.string   "attribute2"
    t.string   "attribute3"
    t.string   "attribute4"
    t.string   "attribute5"
    t.string   "attribute6"
    t.string   "attribute7"
    t.string   "attribute8"
    t.datetime "created_at",         :null => false
    t.datetime "updated_at",         :null => false
  end

end
